create table public.sake_reviews (
    id bigint generated by default as identity not null,
    sake_id bigint not null,
    user_id uuid not null,
    evaluation bigint not null,
    review text not null default ''::text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint sake_reviews_pkey primary key (id),
    constraint sake_reviews_sake_id_fkey foreign key (sake_id) references sakes (id),
    constraint sake_reviews_user_id_fkey foreign key (user_id) references auth.users (id)
) tablespace pg_default;

create table public.sakes (
    id bigint generated by default as identity not null,
    name character varying not null default ''::character varying,
    prefecture bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint sakes_pkey primary key (id)
) tablespace pg_default;